version: "3.8"


services:
  remote-code-worker:
    container_name: remote-code-worker
    image: remote-code-worker:latest

    build:
      context: ./
      dockerfile: ./Dockerfile

    networks:
      - remote_code_net

    environment:
      HOST_NFS_PATH: ${PWD}/../NFS_SHARED_FILE/

    labels:
      - "traefik.enable=false"

    volumes:
      - type: bind
        source: $PWD/../../NFS_SHARED_FILE
        target: /application_storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

    restart: unless-stopped


networks:
  remote_code_net:
    external: true
