version: "3.8"


services:
  remote-code-db:
    container_name: remote-code-db
    image: postgres

    env_file:
      - postgress_db/runtime.env
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'

    expose:
      - "5432"

    volumes:
      - type: volume
        source: postgres_db
        target: /var/lib/postgresql/data

      - type: bind
        source: ./postgress_db/init_script/
        target: /docker-entrypoint-initdb.d

    restart: unless-stopped


networks:
  remote_code_net:
    external: true

volumes:
  postgres_db:
