version: "3.8"


services:
  remote-code-db:
    container_name: remote-code-db
    image: postgres

    env_file:
      - postgress_db/runtime.env
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'

    expose:
      - "5432"

    networks:
      remote_code_net:

    labels:
      - "traefik.enable=false"


    volumes:
      - type: volume
        source: postgres_db
        target: /var/lib/postgresql/data

      - type: bind
        source: ./postgress_db/init_script/
        target: /docker-entrypoint-initdb.d

    restart: unless-stopped

  reverse-proxy:
    container_name: traefik-proxy
    image: traefik:v2.2

    ports:
      # Front ports (must have 80 for ACME protocol)
      - "158.38.65.210:80:80"
      - "158.38.65.210:443:443"
      - "8090:8080"

    env_file:
      - ./traefik/godady_api.env
    #    environment:
    #      GODADDY_API_KEY: ${API_KEY}
    #      GODADDY_API_SECRET: ${API_SECRET}
    #

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${PWD}/traefik/config/traefik.yml
        target: /etc/traefik/traefik.yml
      - type: bind
        source: ${PWD}/traefik/config/acme
        target: /etc/traefik/acme


    networks:
      - remote_code_net


networks:
  remote_code_net:
    external: true


volumes:
  postgres_db:
