version: "3.8"


services:

  remote-code-auth:
    container_name: remote-code-auth
    image: remote-code-auth:latest
    build:
      context: ./../core/
      dockerfile: ./Dockerfile


    labels:
      - "traefik.http.routers.auth.rule=Host(`api.remote-code.woldseth.xyz`) && PathPrefix(`/auth/`)"


    expose:
      - "9080"
      - "9443"

    env_file:
      - ./runtime_envs/db_login.env
      - ./runtime_envs/default_users.env

    volumes:
      - type: volume
        source: token_key_storage
        target: /aplication_storage/token_key

    networks:
      - remote_code_net

networks:
  remote_code_net:
    external: true

volumes:
  token_key_storage:
