version: "3.8"

services:

  reverse-proxy:
    container_name: traefik-proxy
    image: traefik:v2.2

    ports:
      # Front ports (must have 80 for ACME protocol)
      - "158.38.65.10:80:80"
      - "158.38.65.10:443:443"
      - "8090:8080"

    env_file:
      - godady_api.env
    #    environment:
    #      GODADDY_API_KEY: ${API_KEY}
    #      GODADDY_API_SECRET: ${API_SECRET}


    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${PWD}/config/traefik.yml
        target: /etc/traefik/traefik.yml
      - type: bind
        source: ${PWD}/config/acme
        target: /etc/traefik/acme


    networks:
      - remote_code_net

networks:
  remote_code_net:
    external: true
