#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $USER_USERNAME;
ALTER USER $USER_USERNAME WITH PASSWORD '$USER_PASSWORD';
EOSQL

for DB_NAME in $DB_NAMES
do
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE DATABASE $DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $USER_USERNAME;
EOSQL
done