version: "3.8"


services:

  remote-code-master:
    container_name: remote-code-master
    image: remote-code-master:latest
    build:
      context: ./
      dockerfile: ./Dockerfile


    expose:
      - "9080"
      - "9443"

    env_file:
      - ./db_login.env
      - ./kafka.env

    volumes:
      - type: bind
        source: $PWD/../../NFS_SHARED_FILE
        target: /application_storage/shared_files

    networks:
      - remote_code_net

networks:
  remote_code_net:
    external: true

